openapi: 3.0.3
info:
  version: 1.0.0-SNAPSHOT
  title: Catlean Monolithic Frontend API
servers:
  - url: http://localhost:9999
    description: Local
  - url: https://api-staging.catlean.fr
    description: Staging

paths:
  /api/v1/me:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - User
      summary: Get Current Logged In User
      operationId: getCurrentUser
      description: |
        Get Current Logged In User
      responses:
        "200":
          description: 'Successfully current user'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentUserResponseContract'
              example:
                user:
                  id: 818e351a-0421-11ed-b939-0242ac120002
                  email: john.doe@catlean.fr
                  organization:
                    id: 42
                    name: Catlean
                errors:
                  { }
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "500":
          description: An internal error has occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatleanErrorsContract'
              example:
                errors:
                  - code: "T.POSTGRES_TIMEOUT"
                    message: "Failed to open connection with database"
  /api/v1/pull-request/histogram:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - PullRequest
      summary: Get PullRequest Histogram
      operationId: getPullRequestHistogram
      description: |
        Get PullRequest Histogram
      parameters:
        - in: query
          name: organization_name
          schema:
            type: string
            example: armis
        - in: query
          name: team_name
          schema:
            type: string
            example: data-team
        - in: query
          name: histogram_type
          schema:
            type: string
            example: size-limit
      responses:
        "200":
          description: 'Successfully retrieved pull request histogram'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HistogramResponseContract'
              example:
                data:
                  - start_date_range: 12/08/1992
                    data_above_limit: 11
                    data_below_limit: 22
                  - start_date_range: 24/09/1992
                    data_above_limit: 1
                    data_below_limit: 10
                errors:
                  { }
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatleanErrorsContract'
        "500":
          description: An internal error has occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatleanErrorsContract'
              example:
                errors:
                  - code: "T.POSTGRES_TIMEOUT"
                    message: "Failed to open connection with database"
  /api/v1/me/organization:
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - User
      summary: Link Current Logged In User to Organization
      operationId: linkCurrentUserToOrganization
      description: |
        Link Current Logged In User to Organization based on vcs external id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LinkOrganizationToCurrentUserRequestContract'
      responses:
        "200":
          description: 'Successfully linked organization to current user'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentUserResponseContract'
              example:
                user:
                  id: 818e351a-0421-11ed-b939-0242ac120002
                  email: john.doe@catlean.fr
                  organization:
                    id: 42
                    name: Catlean
                errors:
                  { }
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "500":
          description: An internal error has occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatleanErrorsContract'
              example:
                errors:
                  - code: "T.POSTGRES_TIMEOUT"
                    message: "Failed to open connection with database"
  /api/v1/repository:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - Repository
      summary: Get repository linked to current user organization
      description: |
        Get repository linked to current user organization
      responses:
        "200":
          description: 'Successfully get repositories linked to current user organization'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRepositoriesResponseContract'
              example:
                repository:
                  - id: 11111
                    name: repo-1
                  - id: 22222
                    name: repo-2
                  - id: 33333
                    name: repo-3
                errors:
                  { }
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "500":
          description: An internal error has occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatleanErrorsContract'
              example:
                errors:
                  - code: "F.REPOSITORIES_NOT_FOUND"
                    message: "Failed to find repositories"

  /api/v1/team:
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - Team
      summary: Create a team linked to the authenticated user organization
      operationId: createTeam
      description: |
        Create a team linked to the authenticated user organization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTeamRequestContract'
      responses:
        "200":
          description: 'Successfully create team linked organization to current user'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTeamResponseContract'
              example:
                team:
                  id: 818e351a-0421-11ed-b939-0242ac120002
                  name: first-team
                  repository_ids: [ 1,2,3 ]
                errors:
                  { }
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "500":
          description: An internal error has occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatleanErrorsContract'
              example:
                errors:
                  - code: "T.POSTGRES_TIMEOUT"
                    message: "Failed to open connection with database"


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  schemas:
    CatleanErrorsContract:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/CatleanErrorContract'
    CatleanErrorContract:
      type: object
      required:
        - code
        - message
        - metadata
      properties:
        code:
          type: string
          example: F.NOT_FOUND
        message:
          type: string
          example: Histogram not found
        metadata:
          type: object
    HistogramDataResponseContract:
      required:
        - start_date_range
        - data_above_limit
        - data_below_limit
      properties:
        start_date_range:
          type: string
          example: 12/08/1992
        data_above_limit:
          type: integer
          example: 95
        data_below_limit:
          type: integer
          example: 111
    HistogramResponseContract:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/HistogramDataResponseContract'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/CatleanErrorContract'
    OrganizationContract:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
          example: 8ad1c7ea-0421-11ed-b939-0242ac120002
        name:
          type: string
          example: Catlean
    OnboardingContract:
      type: object
      required:
        - has_connected_to_vcs
        - has_configured_team
      properties:
        has_connected_to_vcs:
          type: boolean
        has_configured_team:
          type: boolean
    UserContract:
      type: object
      required:
        - id
        - email
        - organization
        - onboarding
      properties:
        id:
          type: string
          format: uuid
          example: 16
        email:
          type: string
          example: john.doe@catlean.fr
        organization:
          $ref: '#/components/schemas/OrganizationContract'
        onboarding:
          $ref: '#/components/schemas/OnboardingContract'
    CurrentUserResponseContract:
      type: object
      required:
        - user
        - organization
      properties:
        user:
          $ref: '#/components/schemas/UserContract'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/CatleanErrorContract'
    LinkOrganizationToCurrentUserRequestContract:
      type: object
      required:
        - externalId
      properties:
        externalId:
          type: string
          example: 123456543
    GetRepositoriesResponseContract:
      type: object
      properties:
        repositories:
          type: array
          items:
            $ref: '#/components/schemas/RepositoryResponseContract'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/CatleanErrorContract'
    RepositoryResponseContract:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
    CreateTeamRequestContract:
      type: object
      properties:
        name:
          type:
            string
        repository_ids:
          type: array
          items:
            type: integer
    CreateTeamResponseContract:
      type: object
      properties:
        team:
          type: object
          properties:
            id:
              type: string
              format: uuid
            name:
              type: string
            repository_ids:
              type: array
              items:
                type: integer
        errors:
          type: array
          items:
            $ref: '#/components/schemas/CatleanErrorContract'